### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by VictorioBerra** [fschultz/Kaliko.Logger#4]
I cant find documentation anywhere. Just by reading some of the source it looks like I have to add the config information into an App.Config or something?

**Comment by fschultz** [comment]
I apologize for the current lack of documentation, will fix it.

You need to add a new section to your config-file and in that section add the loggers you want, for example:

```
<configuration>
  <configSections>
    <section name="loggers" type="Kaliko.Configuration.LoggersSection, Kaliko.Logger" />
  </configSections>
  <loggers>
    <fileLogger filename="|DataDirectory|my-log-%yyyy%mm.txt" treshold="Major" />
  </loggers>
</configuration>
```

|DataDirectory| in the example above will be replaced with the projects App_data folder but could be a normal path (like c:\temp\my-log.txt).

**Comment by VictorioBerra** [comment]
No worries, I just figured it out when I googled Configuration section it all made sense.

**Comment by fschultz** [comment]
Great! Hope you'll find the project useful :)
